// Why is this not a JSON file? Because if you do it like this you don't need to run the directory as a server to get the data.
window.COURSE_DATA_LOADED = true;
export const PREREQUISITE_AND = 1;
export const PREREQUISITE_REQUIRED = 1;
export const PREREQUISITE_OR = 2;
export const PREREQUISITE_RECOMMENDED = 3;
export const PREREQUISITE_NONE = 4;

export const LOCAL_EXAM = 0;
export const REGENTS_EXAM = 1;
export const AP_EXAM = 2;
export const AP_EXAM_ENCOURAGED = 3;
export const PROJECT = 4;
export const REGENTS_EXAM_JANUARY = 5;

export const ENGLISH_CREDIT = 0;
export const SOCIAL_STUDY_CREDIT = 1;
export const MATH_CREDIT = 2;
export const SCIENCE_CREDIT = 3;
export const HEALTH_CREDIT = 4;

export const MEETS_COMMENCEMENT_CREDIT = 5;
export const MUSIC_SKILLS_DEVELOPMENT_CREDIT = 6;
export const MUSICAL_KNOWLEDGE_ATTITUDE_DEVELOPMENT_CREDIT = 7;
export const GENERAL_MUSIC_CREDIT = 8;

export const PHYSICAL_EDUCATION_CREDIT = 9;
export const WORLD_LANGUAGE_CREDIT = 10;

export const FULL_YEAR = 0;
export const HALF_YEAR = 1;
export const Courses = [
    {
        // MARK: ENGLISH
        name: "English 9R",
        cid: "0003",
        grade: [9],
        exams: [LOCAL_EXAM],
        credits: [[ENGLISH_CREDIT, 1]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "English 10R",
        cid: "0005",
        grade: [10],
        exams: [LOCAL_EXAM],
        credits: [[ENGLISH_CREDIT, 1]],
        prerequisites: ["English 9R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Pre-AP English 2",
        cid: "0070",
        grade: [10],
        exams: [LOCAL_EXAM],
        credits: [[ENGLISH_CREDIT, 1]],
        prerequisites: ["English 9R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "English 11R",
        cid: "0007",
        grade: [11],
        exams: [REGENTS_EXAM],
        credits: [[ENGLISH_CREDIT, 1]],
        prerequisites: ["English 10R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "AP English Language & Composition",
        cid: "0019",
        grade: [11],
        exams: [REGENTS_EXAM, AP_EXAM_ENCOURAGED],
        credits: [[ENGLISH_CREDIT, 1]],
        prerequisites: ["English 10R", "Pre-AP English 2"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "AP Literature & Composition",
        cid: "0020",
        grade: [12],
        exams: [AP_EXAM_ENCOURAGED],
        credits: [[ENGLISH_CREDIT, 1]],
        prerequisites: ["English 11R", "AP English Language & Composition"],
        prerequisite_types: [PREREQUISITE_REQUIRED, PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "College Composition (ENG 101)",
        cid: "0021",
        grade: [12],
        exams: [],
        credits: [[ENGLISH_CREDIT, 0.5]],
        prerequisites: ["English 11R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: true,
    },
    {
        name: "Creative Nonfiction H",
        cid: "0072",
        grade: [12],
        exams: [LOCAL_EXAM],
        credits: [[ENGLISH_CREDIT, 0.5]],
        prerequisites: ["English 11R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: true,
    },
    {
        name: "Creative Writing",
        cid: "0023",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[ENGLISH_CREDIT, 0.5]],
        prerequisites: ["English 9R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Introduction to Film Studies",
        cid: "0030",
        grade: [10, 11, 12],
        exams: [],
        credits: [[ENGLISH_CREDIT, 0.5]],
        prerequisites: ["English 11R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Music as Literature",
        cid: "0097",
        grade: [12],
        exams: [LOCAL_EXAM],
        credits: [[ENGLISH_CREDIT, 0.5]],
        prerequisites: ["English 11R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Practices of Academic Writing",
        cid: "0069",
        grade: [12],
        exams: [LOCAL_EXAM],
        credits: [[ENGLISH_CREDIT, 0.5]],
        prerequisites: ["English 11R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: true,
    },
    {
        name: "Public Speaking",
        cid: "0044",
        grade: [10, 11, 12],
        exams: ["Final Speech"],
        credits: [[ENGLISH_CREDIT, 0.5]],
        prerequisites: ["English 9R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Science Fiction & Fantasy",
        cid: "0068",
        grade: [10, 11, 12],
        exams: [PROJECT],
        credits: [[ENGLISH_CREDIT, 0.5]],
        prerequisites: ["English 9R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Shakespeare",
        cid: "0032",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[ENGLISH_CREDIT, 0.5]],
        prerequisites: ["English 9R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Sports Literature",
        cid: "0034",
        grade: [10, 11, 12],
        exams: [PROJECT],
        credits: [[ENGLISH_CREDIT, 0.5]],
        prerequisites: ["English 9R"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        // MARK: MATH
        name: "Algebra I",
        cid: "0406",
        grade: [9, 10, 11, 12],
        exams: [REGENTS_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Geometry",
        cid: "0411",
        grade: [9, 10, 11, 12],
        exams: [REGENTS_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Algebra I"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Math III",
        cid: "0410",
        grade: [11, 12],
        exams: [LOCAL_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Geometry"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Algebra II Extended",
        cid: "0442",
        grade: [11, 12],
        exams: [REGENTS_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Geometry"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Algebra II",
        cid: "0440",
        grade: [9, 10, 11, 12],
        exams: [REGENTS_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Geometry"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Algebra II Accelerated",
        cid: "0443",
        grade: [9, 10, 11, 12],
        exams: [REGENTS_EXAM_JANUARY],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Geometry"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Pre-Calculus Accelerated",
        cid: "0414",
        grade: [9, 10, 11, 12],
        exams: [REGENTS_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Geometry"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Math & Financial Applications",
        cid: "0605",
        grade: [11, 12],
        exams: [LOCAL_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Algebra I"],
        prerequisite_types: [PREREQUISITE_RECOMMENDED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Pre-Calculus",
        cid: "0416",
        grade: [11, 12],
        exams: [LOCAL_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Algebra II", "Algebra II Accelerated", "Algebra II Extended"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR, PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Pre-Calculus Honors",
        cid: "0417",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Algebra II", "Algebra II Accelerated", "Algebra II Extended"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR, PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Calculus H (SUPA)",
        cid: "0433",
        grade: [12],
        exams: [LOCAL_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Pre-Calculus", "Pre-Calculus Honors", "Pre-Calculus Accelerated"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR, PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: true,
    },
    {
        name: "AP Calculus BC",
        cid: "0420",
        grade: [11, 12],
        exams: [LOCAL_EXAM, AP_EXAM_ENCOURAGED],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Pre-Calculus", "Pre-Calculus Honors", "Pre-Calculus Accelerated"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR, PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "College Statistics",
        cid: "0449",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["Algebra II", "Algebra II Accelerated", "Algebra II Extended"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR, PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: true,
    },
    {
        name: "Calculus III",
        cid: "0432",
        grade: [12],
        exams: [LOCAL_EXAM],
        credits: [[MATH_CREDIT, 1]],
        prerequisites: ["AP Calculus BC"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: true,
    },
    {
        // MARK: HEALTH
        name: "Health I",
        cid: "0902",
        grade: [9, 10, 11, 12],
        exams: [],
        credits: [[HEALTH_CREDIT, 0.5]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Health II",
        cid: "0903",
        grade: [11, 12],
        exams: [],
        credits: [[HEALTH_CREDIT, 0.5]],
        prerequisites: ["Health I"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Reconnecting Youth",
        cid: "0906",
        grade: [9, 10, 11, 12],
        exams: [],
        credits: [[HEALTH_CREDIT, 0.5]],
        prerequisites: ["Counselor Recommendation"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        // MARK: MUSIC
        name: "Concert Choir",
        cid: "0804",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [
            [MUSIC_SKILLS_DEVELOPMENT_CREDIT, 1],
            [MEETS_COMMENCEMENT_CREDIT, 0],
        ],
        prerequisites: ["Choral Experience", "Able to Match Pitch"],
        prerequisite_types: [PREREQUISITE_RECOMMENDED, PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Chorale",
        cid: "0808",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [
            [MUSIC_SKILLS_DEVELOPMENT_CREDIT, 1],
            [MEETS_COMMENCEMENT_CREDIT, 0],
        ],
        prerequisites: ["Concert Choir", "Solo Voice"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Solo Voice",
        cid: "0800",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[MUSIC_SKILLS_DEVELOPMENT_CREDIT, 1]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Intermediate Voice",
        cid: "0801",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[MUSIC_SKILLS_DEVELOPMENT_CREDIT, 1]],
        prerequisites: ["Solo Voice"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Advanced Voice",
        cid: "0802",
        grade: [11, 12],
        exams: [LOCAL_EXAM],
        credits: [[MUSIC_SKILLS_DEVELOPMENT_CREDIT, 1]],
        prerequisites: ["Solo Voice", "Intermediate Voice", "Teacher Recommendation"],
        prerequisite_types: [PREREQUISITE_REQUIRED, PREREQUISITE_REQUIRED, PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Jazz Choir",
        cid: "0812",
        grade: [9, 10, 11, 12],
        exams: [],
        credits: [[MUSIC_SKILLS_DEVELOPMENT_CREDIT, 0.5]],
        prerequisites: ["Concert Choir", "Chorale", "Audition"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR, PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Select Treble Choir",
        cid: "0832",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[MUSIC_SKILLS_DEVELOPMENT_CREDIT, 0.25]],
        prerequisites: ["Concert Choir", "Chorale", "Audition"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR, PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Music Theory I",
        cid: "0846",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [
            [MUSICAL_KNOWLEDGE_ATTITUDE_DEVELOPMENT_CREDIT, 1],
            [MEETS_COMMENCEMENT_CREDIT, 0],
        ],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "AP Music Theory",
        cid: "0847",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM, AP_EXAM_ENCOURAGED],
        credits: [
            [MUSICAL_KNOWLEDGE_ATTITUDE_DEVELOPMENT_CREDIT, 1],
            [MEETS_COMMENCEMENT_CREDIT, 0],
        ],
        prerequisites: ["Music Theory I", "Teacher Recommendation"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Music in Our Lives",
        cid: "0827",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [
            [MUSICAL_KNOWLEDGE_ATTITUDE_DEVELOPMENT_CREDIT, 1],
            [MEETS_COMMENCEMENT_CREDIT, 0],
        ],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Studio Recording and Sound Engineering",
        cid: "NONE",
        grade: [11, 12],
        exams: [LOCAL_EXAM],
        credits: [[MUSICAL_KNOWLEDGE_ATTITUDE_DEVELOPMENT_CREDIT, 1]],
        prerequisites: ["Audition", "Instructor Approval"],
        prerequisite_types: [PREREQUISITE_OR, PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Concert Band",
        cid: "0820",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [
            [MUSIC_SKILLS_DEVELOPMENT_CREDIT, 1],
            [MEETS_COMMENCEMENT_CREDIT, 0],
        ],
        prerequisites: ["Band Experience"],
        prerequisite_types: [PREREQUISITE_RECOMMENDED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Wind Ensemble",
        cid: "0823",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [
            [MUSIC_SKILLS_DEVELOPMENT_CREDIT, 1],
            [MEETS_COMMENCEMENT_CREDIT, 0],
        ],
        prerequisites: ["Audition"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Jazz Ensemble",
        cid: "0823",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[GENERAL_MUSIC_CREDIT, 0.5]],
        prerequisites: [
            "Audition",
            "Concert Band",
            "Wind Ensemble",
            "Philharmonia Orchestra",
            "Symphony Orchestra",
        ],
        prerequisite_types: [
            PREREQUISITE_REQUIRED,
            PREREQUISITE_OR,
            PREREQUISITE_OR,
            PREREQUISITE_OR,
            PREREQUISITE_OR,
        ],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Jazz Democracy",
        cid: "0829",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[GENERAL_MUSIC_CREDIT, 0.5]],
        prerequisites: [
            "Concert Band",
            "Wind Ensemble",
            "Philharmonia Orchestra",
            "Symphony Orchestra",
        ],
        prerequisite_types: [
            PREREQUISITE_OR,
            PREREQUISITE_OR,
            PREREQUISITE_OR,
            PREREQUISITE_OR,
        ],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Philharmonia Orchestra",
        cid: "0821",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [
            [MUSIC_SKILLS_DEVELOPMENT_CREDIT, 1],
            [MEETS_COMMENCEMENT_CREDIT, 0],
        ],
        prerequisites: ["Orchestra Experience"],
        prerequisite_types: [PREREQUISITE_RECOMMENDED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Symphony Orchestra",
        cid: "0822",
        grade: [9, 10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [
            [MUSIC_SKILLS_DEVELOPMENT_CREDIT, 1],
            [MEETS_COMMENCEMENT_CREDIT, 0],
        ],
        prerequisites: ["Audition"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        // MARK: Physical Education
        name: "Physical Education 9",
        cid: "0900",
        grade: [9],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Physical Education 10",
        cid: "0901",
        grade: [10],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Unified PE",
        cid: "0983",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Yoga",
        cid: "0988",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Adventure Learning",
        cid: "0972",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Dance / Personal Defense",
        cid: "0955",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Fitness for Life",
        cid: "0955",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Golf and Racquet",
        cid: "0953",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Lifeguarding",
        cid: "0975",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: ["Swim Test"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Outdoor Experience",
        cid: "0974",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Sport Education A",
        cid: "0964",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Sport Education B",
        cid: "0966",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Team Games A",
        cid: "0981",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Team Games B",
        cid: "0981",
        grade: [11, 12],
        exams: [],
        credits: [[PHYSICAL_EDUCATION_CREDIT, 0.25]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        // MARK: Science
        name: "Physical Setting: Earth Science Regents",
        cid: "0300",
        grade: [9, 10, 11, 12],
        exams: [REGENTS_EXAM],
        credits: [[SCIENCE_CREDIT, 1]],
        prerequisites: [],
        prerequisite_types: [],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "The Living Environment Regents",
        cid: "0300",
        grade: [9, 10, 11, 12],
        exams: [REGENTS_EXAM],
        credits: [[SCIENCE_CREDIT, 1]],
        prerequisites: ["Physical Setting: Earth Science Regents"],
        prerequisite_types: [PREREQUISITE_RECOMMENDED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Physical Setting: Chemistry Regents",
        cid: "0311",
        grade: [10, 11, 12],
        exams: [REGENTS_EXAM],
        credits: [[SCIENCE_CREDIT, 1]],
        prerequisites: ["Algebra I", "Physical Setting: Earth Science Regents"],
        prerequisite_types: [PREREQUISITE_REQUIRED, PREREQUISITE_RECOMMENDED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Physical Setting: Physics with Optics",
        cid: "0319",
        grade: [10, 11, 12],
        exams: [REGENTS_EXAM],
        credits: [[SCIENCE_CREDIT, 1]],
        prerequisites: ["Algebra II"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: true,
    },
    {
        name: "AP Environmental Science",
        cid: "0307",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM, AP_EXAM_ENCOURAGED],
        credits: [[SCIENCE_CREDIT, 1]],
        prerequisites: [
            "The Living Environment Regents",
            "Physical Setting: Earth Science Regents",
            "Physical Setting: Physics with Optics",
            "Physical Setting: Chemistry Regents",
        ],
        prerequisite_types: [
            PREREQUISITE_REQUIRED,
            PREREQUISITE_OR,
            PREREQUISITE_OR,
            PREREQUISITE_OR,
        ],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "AP Biology",
        cid: "0305",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM, AP_EXAM_ENCOURAGED],
        credits: [[SCIENCE_CREDIT, 1]],
        prerequisites: [
            "The Living Environment Regents",
            "Physical Setting: Chemistry Regents",
        ],
        prerequisite_types: [PREREQUISITE_REQUIRED, PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "AP Chemistry",
        cid: "0313",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM, AP_EXAM_ENCOURAGED],
        credits: [[SCIENCE_CREDIT, 1]],
        prerequisites: ["Physical Setting: Chemistry Regents", "Algebra I"],
        prerequisite_types: [PREREQUISITE_REQUIRED, PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "AP Physics C",
        cid: "0320",
        grade: [11, 12],
        exams: [AP_EXAM_ENCOURAGED],
        credits: [[SCIENCE_CREDIT, 1]],
        prerequisites: [
            "Physical Setting: Physics with Optics",
            "Calculus H (SUPA)",
            "AP Calculus BC",
            "Calculus III",
        ],
        prerequisite_types: [
            PREREQUISITE_REQUIRED,
            PREREQUISITE_OR,
            PREREQUISITE_OR,
            PREREQUISITE_OR,
        ],
        length: [FULL_YEAR],
        dual: false,
    },
    {
        name: "Astronomy",
        cid: "0345",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[SCIENCE_CREDIT, 0.5]],
        prerequisites: [],// MARK: FINISH
        prerequisite_types: [],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Forensic Science",
        cid: "0341",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[SCIENCE_CREDIT, 0.5]],
        prerequisites: ["The Living Environment Regents"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [HALF_YEAR],
        dual: false,
    },
    {
        name: "Forensic Science Honors",
        cid: "0342",
        grade: [11, 12],
        exams: [LOCAL_EXAM],
        credits: [[SCIENCE_CREDIT, 1]],
        prerequisites: ["Physical Setting: Chemistry Regents"],
        prerequisite_types: [PREREQUISITE_REQUIRED],
        length: [FULL_YEAR],
        dual: true,
    },
    {
        name: "Insights into Chemistry",
        cid: "0342",
        grade: [10, 11, 12],
        exams: [LOCAL_EXAM],
        credits: [[SCIENCE_CREDIT, 0.5]],
        prerequisites: [
            "The Living Environment Regents",
            "Physical Setting: Earth Science Regents",
            "Physical Setting: Physics with Optics",
            "Physical Setting: Chemistry Regents"],
        prerequisite_types: [
            PREREQUISITE_OR,
            PREREQUISITE_OR, 
            PREREQUISITE_OR, 
            PREREQUISITE_OR],
        length: [FULL_YEAR],
        dual: false,
    },
];